---
title: "Final Website: AI Usage Statement"
Author: "Addison Dinglasan, Maheep Mudra"
Date: "2026-03-12" 
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Website Prototype: AI Usage Statement}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Generative AI Usage Statement

In accordance with the STA380 website prototype rubric details, this vignette details the specific use of Generative AI (Gemini and ChatGPT) during the transition from a standard R package to a functional Shiny website prototype.

## 1. Debugging and Error Handling 
Generative AI was utilized to debug Shiny error messages. Specifically, we used these tools to resolve non-numeric data extraction errors. These errors were identified as being caused by R's default column renaming behavior during data handling.

## 2. Implementation of UX Validation Functions
AI was used to help implement UX validation functions, specifically 'req()' and 'validate()'. These functions were incorporated to prevent server overload that could result from excessive bootstrap iterations.

## 3. Code Clarification
Generative AI was utilized for clarifying the R code. This was done to ensure the final code base is clean and well-organized for the prototype submission.

## 4. Implementation of "downloadHandler" Function and CSV Export Button Feature
AI was used to understand the underlying logic of the "downloadHandler" function, which provided the technical insight needed to successfully write the comparative statistics table into the final csv export.

## 5. Interactive Data Visualization with "plotly"
AI was used to help integrate and understand the "plotly package and convert static plots into interactive ones using ggplotly(). It specifically helped with the debugging process, ensuring that the interactive hover-text accurately reported the exact difference in means/medians and bin frequencies. This made it easy to improve the overall data legibility and user experience within the shiny application.

## Human Verification
All AI-generated suggestions,including code snippets and debugging logic, were manually reviewed and verified by the authors. We performed localized testing to ensure that the integrated components function as intended and align with the project's goals.
