---
title: "Data anlysis"
Author: "Maheep Mundra"
Date: "2026-02-24"
output: html_document
----
# Import libraies and methods
```{r}
library(tidyverse)
library(ggplot2)
library(knitr)
source("submissions/BasicImplementation/bootstrap.R")
```
# Load Data
```{r}
lizard_data <- read.csv("submissions/BasicImplementation/data.csv",
 fileEncoding = "latin1")

# Inspect data
print(head(lizard_data, 5))
```
# Clean up data
```{r}
#Clean names replace . with _ between word spaces,
#remove white spaces and lowercase
colnames(lizard_data) <- tolower(gsub(" ", "_", trimws(gsub("\\.+", " ", colnames(lizard_data)))))

#Print the first 50 entries of data set
print(head(lizard_data, 50))
#Print Size of data set
print(dim(lizard_data))

#Remove rows with missing sex, snout_vent_length_mm or body_temperature_c
clean_data <- lizard_data %>% 
    filter(
    !is.na(sex),
    !is.na(snout_vent_length_mm),
    !is.na(body_temperature_c))

#Print the first 5 entries of data set
print(head(clean_data, 5))
#Print Size of data set
print(dim(clean_data))
```
# Extract data
```{r}
# Snout Length values
male_snout_len <- clean_data[    # Male snout length
    clean_data["sex"] == "M",
    "snout_vent_length_mm"]
print(head(male_snout_len, 5))

female_snout_len <- clean_data[  # Female snout length
    clean_data["sex"] == "F",
    "snout_vent_length_mm"]
print(head(female_snout_len_snout_len, 5))

# Body Temps
f_gravid_btemp <- clean_data[     # Body temp of pregnant females
    clean_data["reproductive_status"] == "gravid",
    "body_temperature_c"]
print(head(f_gravid_btemp, 5))

f_nongravid_btemp <- clean_data[  # Body temp of non-pregnant females
    clean_data["reproductive_status"] == "nongravid",
    "body_temperature_c"]
print(head(f_nongravid_btemp, 5))

m_btemp <- clean_data[    # Male body temp
    clean_data["sex"] == "M",
    "body_temperature_c"]
print(head(m_btemp, 5))
```